---
title: "European drama around tanks for Ukraine"
description: |
  How to sidestep a red line
author:
  - name: Julian Barg
    url: https://jbarg.net
date: 2023-01-22
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Interesting events playing out at the moment around German tanks for Ukraine. Here is my interpretation. Pure speculation, I don't have more information than anybody else. And absolutely no revising of this text, this is just going to be pure flow consciousness. 

So several European countries would like to send German Leopard 2 tanks to Ukraine. Germany is apprehensive, and needs to approve any exports. Now, previously the German government had been secretive about weapons exports to Ukraine a couple of times, denying that they were going to send weapons until after the fact. In this specific case, tanks are a--perceived or real--red line that the German government did not want to transgress. A previous example were missile defense systems, and before that multiple rocket launchers like HIMARS.

The funny thing is, now other European countries--particularly Poland--make it appear as though Germany's hands are tied. They suggest that they may export German tanks without permission from Germany. Now let's imagine for a second that tanks are a real red line, that some member of the Russian government has told some member of the German government that if Germany was to approve exports of German tanks to Ukraine, something would happen. Then the current situation would be sidestepping the red line on the basis of a technicality--"but we did not approve those exports!" Knowing that the German government likes to stage weapons deliveries as not happening, it would not be unthinkable that this whole situation is completely orchestrated. And my best guess is that if Poland exports tanks without permission, the German government will quietly approve those exports after the fact. Regardless, the fact that Poland is driving the current debate--respect, the Poles are punching massively above their weight. Everybody expected the US or Germany to make the calls, but Poland is sneaking up on the world stage.
