---
title: "Footnote 2021-07-19--discourse"
description: |
  (No description available)
author:
  - name: Julian Barg
    url: https://jbarg.net
date: 07-19-2021
output:
  distill::distill_article:
    self_contained: false
bibliography: ../../library.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Just read @Leibel2018. I few things stand out to me. First, how few papers there are in the area. They review 61 articles, including papers on _discourse_, _rhetorics_, and _frames_. Then, how little the literature concerns itself with dialogue and interaction--as opposed to statements that are issued and read by allies only. The insular nature of society media is reflected in our research. There is a lack of dyadic relationships, or, for the lack of a better word, networks. Not in a quantitative network analysis kind of way--that may in most cases just reinforce insularity--but in a very simple "who says what to whom, and what happens then" way. That is how insularity comes to be. How is it that the few times where A says something to X rather than B and C--A being similar to B and C but not X--it is so easy for X to dismiss that message? In a similar vain, the dearth of qualitative work in the area after the linguistic turn we supposedly have taken. Sure, quantifying discourse language is convenient, but on many of the _big, important issues_, the fronts are quite clear. For instance, interest groups such as indigenous people say what they think, with much clarity. There is no need to code the language just to decode it again. I don't think the supposed hidden messages exist--the only thing that may be hidden away is part of the discourse, and it takes a good researcher to surface relevant documents (I know this conflicts with the previous sentence, leave me alone!).

I do suspect though that there is some additional, older research--especially mixed methods with archival work and interviews--that could be interpreted as being concerned with discourse, but which lacks the clear methods section to make the link.
