---
title: "Document archive"
description: |
  A list of documents I archived in case they disappear, or because I *will* forget where to find them. Also, makes it easier to search and find them.

author:
  - name: Julian Barg
    url: https://jbarg.net
date: "`r Sys.Date()`"
output: distill::distill_article
bibliography: library.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## 2022

* Keystone Final Environmental Impact Statement 2008
  * Source: https://www.energy.gov/nepa/eis-0410-keystone-oil-pipeline-project
  * https://drive.google.com/uc?format=pdf&id=1Gbxxn8NGrZrL1B5PddMAbFVD05kAi6gH
* KXL Environmental Report November 2008
  * Source: https://2012-keystonepipeline-xl.state.gov/archive/proj_docs/env/index.htm
  * https://drive.google.com/uc?format=pdf&id=1iPEWDfBg0fxTXuJGU0otGtal_vTL-yQ3
* KXL Draft EIS (2010)
  * Source: https://2012-keystonepipeline-xl.state.gov/archive/dos_docs/deis/index.htm
  * https://drive.google.com/uc?format=pdf&id=1ooepDULXdt5sOAYiKPm6fhY6-tso3NTT
* KXL Final EIS (2011)
  * Source: https://2012-keystonepipeline-xl.state.gov/archive/dos_docs/feis/index.htm
  * https://drive.google.com/uc?format=pdf&id=1Y9aflCOQpJd0hETzAx8JABE-qGeCEHnh
* 2013-01-03 KXL Draft EIS
  * Source: https://2012-keystonepipeline-xl.state.gov/draftseis/index.htm
  * https://drive.google.com/uc?format=pdf&id=1SwSXEct5uQlHdwbcOGJQiCUHVh-SfKDZ
* 2014-01-01 KXL Final Supplemental EIS
  * Source: https://2012-keystonepipeline-xl.state.gov/finalseis/index.htm
  * https://drive.google.com/uc?format=pdf&id=1gioIRBMQ01UZI98nrN6ZwINQS1j8R--i
* 2018-07-26 Draft Environmental Assessment
  * Source: https://2017-2021.state.gov/releases-keystone-xl-pipeline/index.html
  * https://drive.google.com/uc?format=pdf&id=1qVZnT7twpeKqy29OhrZu_VfsNLVhGRqh
* 2019-10-01 KXL Draft Supplemental EIS
  * Source: https://2017-2021.state.gov/releases-keystone-xl-pipeline/index.html
  * https://drive.google.com/uc?format=pdf&id=1qVZnT7twpeKqy29OhrZu_VfsNLVhGRqh
* 2019-12-01 KXL Final Supplemental EIS
  * Source: https://2017-2021.state.gov/releases-keystone-xl-pipeline/index.html
  * https://drive.google.com/uc?format=pdf&id=1tfAtTAqMHGH8JAqNxRL-K4LuAVKBj-Qn
* Nebraska Legislature exhibits 2011-02-09
  * https://drive.google.com/uc?format=pdf&id=1x4GmdoSC362UyV6Hi27fkJnBLOtG93OW

## 2021

### November

* Whistleblower report on ALEC (American Legislative Exchange Council) by the IRA including ALEC strategy documents and many documents on Exxon and it's relationship with ALEC.
  * https://drive.google.com/uc?format=pdf&id=1tJZIN0P0VwiMtIeyT_9xRvZVOeTvYTyc
* Leaked Stratfor strategy document for Suncor that details their strategy for handling environmental groups. Identifies four categories: idealists, radicals, realists, and opportunists. For example, Greenpeace is identified as radical, Sierra club as idealist, NWF & WWF as realist. Suggests different alternatives in terms of strategic responses, such as stalling and strategic silence, but also rapid negotiations or structured dialogue.
  * 
* Tigerswan intelligence briefing for Energy Transfer Partners on anti-DAPL protest at Standing Rock, dated 2016-10-20. Includes personal details, such as the phone number and photo of one protester that successfully gathered intel on ETP in Iowa.
  * https://drive.google.com/uc?format=pdf&id=1Add0HDQM8UCFA2rLdiKQWPIRN5i80iy9
  * Source: https://theintercept.com/2017/05/27/leaked-documents-reveal-security-firms-counterterrorism-tactics-at-standing-rock-to-defeat-pipeline-insurgencies/
  * Other documents: https://www.documentcloud.org/app?q=%2Bproject%3Atigerswan-33327
* ALEC email on the Oil Sands Academy in Alberta. The academy hosted many US lawmakers and was its sponsors include Shell, TransCanada, and the 
Canadian Association of Petroleum Producers.
  * https://drive.google.com/uc?format=pdf&id=1SfDYuplH2HMFcpVdFMESUUFay2jU_3Mp
* Friends of the earth FOIA documents including emails between TransCanada and State Department
  * https://drive.google.com/uc?format=pdf&id=1vefLnyuY_zmvTQNvKjKnocspVm_38W2V
  * Original lot: https://www.dropbox.com/sh/eepxidnpb7sfvne/AAAiRLyqmOOUqQFkM5lpZCUWa/Aug%205%202011
  * More information: https://foe.org/blog/2014-02-keystone-documents/
  * Story 1--State Department potential bias: https://foe.org/blog/new-keystone-xl-documents-raise-fresh-concerns-about-state-department/
  * Story 2: https://foe.org/blog/2011-10-documents-reveal-smoking-gun-regarding-state-departm/
* US Energy Information Administration data on pipelines, operators and locations
  * https://drive.google.com/uc?export=download&id=1GeAeATGNbNa7nJHaMGuj0tW5LzNZo4_G
  * https://drive.google.com/uc?export=download&id=1SIJw_vzdSzbSMgyOiBiXF7gmv4ELfCB5
  * Source: https://www.eia.gov/maps/layer_info-m.php
