---
title: "Language and Institutions"
description: |
  (No description available)
author:
  - name: Julian Barg
    url: https://jbarg.net
date: 09-01-2021
output:
  distill::distill_article:
    self_contained: false
bibliography: ../../library.bib
---

_How does language bless us with institutions?_ The institution does not have an existence that is independent from language. Institutions are characterized by a _taken-for-grantedness_ [@Steele2021]. A language exchange is never without precedence and accordingly, we expect responses to fall into a certain "range"--for the lack of a better term. Responses are not chosen from the infinite pool of all possible things that _could_ be said. Language games can become incredibly complex, and in many cases are interrelated. @Bourdieu1977 shall serve as an illustrative and comprehensive example. His study on the society of Algeria works its way up all the way from the micro to the macro. The foundation of his analysis are common words and phrases used in Algeria, and their rationales. He then works his way up to describe the relationship between these words and phrases and common power structures in Algeria--most notably between a bonded person and the master. Bourdieu's constructivist stance does not preclude the analysis of nonsocial factors (that are of course still only accessed through social means, i.e., ethnographic and archival work). The seasons take an important role--they primarily influence the activities that Algerians pick up and put to rest throughout the year. The rarity of money necessitates the accumulation of symbolic rather than economic capital.

_How does the literature describe institutions?_ In the OT literature, the _institution_ is a convention for talking about a specific context. Note that many of the classic works in sociology, including @Bourdieu1977, do not typically hone in on a specific institution. Rather, Bourdieu uses "institution" as an umbrella term for "myths, rites, or bodies of law, or [...] co-ordination" [@Bourdieu1977, p. 79] that have come to be taken for granted, but barely ever names a specific institution. In the OT literature, we typically move in a world that is the aggregate of a countable number of specific institutions (this is admittedly a bit of a hyperbole). Sociologists such as Bourdieu move in a space that consists of many overlapping and interrelated conventions. Some of these conventions are so complex and ingrained that should be considered institutions. To define thresholds or boundaries would defy the spirit of that literature.

_What is the institution in my context?_ There are many things in my context that have become to be taken for granted. Because of their taken-for-grantedness, they often are most visible in retrospect--when their taken-for-grantedness has lapsed. The oil industry itself is an institution--says _The Guardian_: "The fossil-fuel industry’s aura of invincibility is gone" [@McKibben2015]. The approval of construction permits had been taken for grated--says _World Oil_: "Keystone XL shutdown may signal the end of major U.S. oil infrastructure" [@Freitas2021]. 

Pipeline safety had been institutionalized, but in a more "regular" fashion. The safety of the pipeline post construction is strictly kept out off the agenda in state-level meetings and hearings. While right-of-way is handled at the state level, pipeline safety is regulated at the federal level. In practical terms, this means that states are not allowed to make decisions on pipeline permits based on the anticipated safety--or lack thereof--of the pipeline. This division of roles is enforced vigorously. Possibly because TransCanada's lawyers have advised the authorities in charge that it will sue if there is any indication of bias based on pipeline safety issues? This I should investigate further, possibly in interviews. 

The government is also an institution, one that is enforced quite viciously. This point is more salient with the Dakota Access Pipeline but also present in the case of Keystone XL. Where there is an indication that protesters may circumvent the government and take it on themselves to block the construction of the pipeline there are both responses that take advantage of existing regulations--think trespassing--and there are actors that take it upon themselves on enforcing the institution and countering any threat from protesters on a level that goes beyond their job description. Many local police offices go out of their way to assist TransCanada. 

Sometimes, the lines between institutions are blurry. In the case of the Dakota Access Pipeline, Energy Transfer Partners often compensated police departments--a lucrative deal for cash-strapped rural police departments. TransCanada has also been assisting police departments with "intel" on specific protesters. And independent of Keystone XL and the Dakota Access Pipeline, the American Legislative Exchange Council has successfully "shopped around" a model bill to states--the Critical Infrastructure Protection Act--which introduces severe punitive measures against protesters that trespass on energy facilities such as pipelines [@ALEC2018; @Kaufman2020]. In the US, information on the exact location of pipelines is only accessible for government officials, pipeline operators, and contractors, meaning that protesters can unknowingly trespass on this infrastructure. The bill highlights the blur or network that can emerge between institutions.
