---
title: "Wet'suwet'en--a short note"
description: |
  Writing down what I know--which isn't much, but otherwise I will definitely forget
author:
  - name: Julian Barg
    url: https://jbarg.net
date: 12-20-2021
output:
  distill::distill_article:
    self_contained: false
bibliography: ../../library.bib
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

So after failing with Keystone XL, TC Energy (formerly TransCanada) is now working hard on its Coastal Gaslink Pipeline. The Coastal GasLink Pipeline transports fossil gas in a liquid state rather than oil or oil sands. But it adresses one of the same challenges that Keystone XL meant to tackle: the difficulty of cutting through the rockies and the Fjords of the British Columbia Coast. British Columbia is also unique in that about 95% of the area is unceded territory, meaning that no contracts were signed when Canada colonized this territory. In the same breath, these territories are also often described as being stolen--a pretty accurate description. Since TC Energy couldn't be too picky with their route, it should come as no surprise that some conflicts arose.

I have been reading up on the events that transpired so far on Twitter and other websites occasionally. So I just got a glimpse of the events. But there is so much there that I now felt the need to write it down, lest I forget.

Of course TC Energy knows the laws on indigenous consultation, and in this case, too, indigenous communities were formally consulted and agreements were reached. One curiosity though is how the indigenous communities in BC are organized. Since most of the land is unceded, reserves only make up for a small fraction of indigenous territories. Reserves have formal indigenous governments, but participation in the elections is negligible--in that context the Indian Act is often cited with slowly eroding "formal" membership numbers. And then there are the unceded territories outside of the reserves. These often have the formal status of "Crown Land"--however, the Supreme Court of Canada has begun recognizing that indigenous people have at least some rights over there lands. Which indigenous people though? 

The elected governments of the reservations only have jurisdiction over the territory of the reservation. This is a system that was imposed on the indigenous population. Outside the reservations, indigenous people are organized like any informal community is: loosely. Clans are families, and they are neighbors. Less than 200,000 First Nations lived in British Columbia--on an area that is larger than Germany and France combined. That means that indigenous people are not a "member of a clan" in any abstract sense--they are aunts and uncles, cousins and second cousins. And another clan is an important neighbor rather than any abstract external "government entity". On the other hand, some indigenous people are also formally organized as bands under the Indian Act. The 2014 transfer of a Crown Land land title in a different part of BC to the Tsilhqot'in by the Supreme Court of Canada also adds to the uncertainty around indigenous identity and formal jurisdiction.

In some of the regions which Coastal Gaslink Pipeline would cross, indigenous communities came together--as families and neighbors, but also as activists--and reached an agreement: they would not allow TC Energy to stand. Take a couple of extended families, and their neighbors a couple miles over, and their extended families--and you end up with a couple of hundred or thousand indigenous people unequivocally opposed to the pipeline project. In this specific case, these couple of thousands are members of indigenous communities that do not live on the reserves and were not consulted by TC Energy during the planning process for the Coastal Gaslink Pipeline.  They would also not benefit from whatever funds TC Energy has allocated to recognized indigenous governments [compare to and contrast with @Suncor2021].

Now the twist: these are Crown Lands we are talking about, who has the authority to speak for First Nations there? Not the reserve governments--their jurisdiction ends at the border of the reserves. The bands? Maybe, but if that is the case, which band should be given the right to exert which authorities over which lands? The indigenous communities involved in these events also have matrilineal traditions which were superseded by the Indian Act. The matrilineal tradition may be a better representation of how the clans are organized, although in practice it is more complicated than that.

This is what happened so far: on January 5, 2020 the Wet'suwet'en issue an eviction notice to Coastal GasLink contractors [@Dryden2020], signed by 8 hereditary chiefs. A BC court issued an injunction against this order only two days later, which TC Energy now uses to legitimize its continued work. Regardless, on November 15, 2021, the Wet'suwet'en decided to enforce the eviction order by erecting a checkpoint and blocking the only access to the area [@Wilson2021]. Only a few days later RCMP members were flown in by the province during a historic flooding. The Gidimt'en checkpoint was raided and the hereditary chiefs arrested in a pretty gruesome fashion--after the raid, a member of the press was held for four days and three nights [@Bracken2021]. Undeterred, when the Wet'suwet'en members were released, they reoccupied their site and continued their eviction: 
https://twitter.com/gidimten/status/1472644113434513409

What is notable is the evolution of indigenous resistance at play here. The Wet'suwet'en no longer use the language of indigenous tradition and cultural practices, but assert their rights using the language of law: an *eviction order* is *executed*. In conjunction with the legal challenges that Crown Land in BC faces, there is an interesting question here. Will these just continue as inconsequential language games? Or is this a form of institution building, growing out of an evolved indigenous identity? The events may pose a challenge to the previously untouchable Canadian institution that is the fossil fuel industry. Coastal GasLink has already been delayed, and TC Energy seems "weakened", for the lack of a better term, after the Keystone XL defeat.

The literature would speak of deinstitutionalization, but I see this rather (or in addition) as potentially a new institution emerging, in response to the challenges posed by an existing institution or institutions to a population. Of interest is also the hereditary chiefs' identity. Whereas the reserves and elected band officials support the pipeline, the hereditary chiefs stand united in opposition. Of course there are the financial incentives that hereditary chiefs are excluded from, but there is also their unique, historically-culturally rooted identity.
