---
title: "How to look at discourse"
description: |
  A short description of the post.
author:
  - name: Julian Barg
    url: https://jbarg.net
date: 08-14-2021
output:
  distill::distill_article:
    self_contained: false
bibliography: ../../library.bib
---

All organizational processes are inherently discursive. If they were not discursive, they would not be social, and hence could not be organizational. Organizational processes always involve multiple individuals, and when one individual takes an action--think a manager defining a task or providing a tool--this action "brushes up" against the understanding of other members of the organization. At the center of this process are signs or signifying work--the construction or utilization of signs such as the spoken word. A functional sign has many stable associations that can be utilized in social action. In the best case, the difference in understanding is marginal, there is very little "noise" or interference. But what is associated with a sign will never be entirely identical between two individuals-- 

we take larger processes so discourse is more clear

how to analyze them?

let's look at models
