---
title: "Brexit negotiations--the full story"
description: |
  [The FT has written a big tell-all about the Brexit negotiations.](https://www.ft.com/content/cc6b0d9a-d8cc-4ddb-8c57-726df018c10e) It's getting quite clear that Boris Johnson has traded everything--EVERYTHING!--he had on the table for sovereignty. Sovereignty as the highest priority. Higher than anything else. "The process just wasn’t driven by thinking about what the UK really wanted from a deal, but to justify the claims to sovereignty. It was quite astonishing" says one government official. (cont.)
author:
  - name: Julian Barg
    url: https://jbarg.net
date: 01-22-2021
output:
  distill::distill_article:
    self_contained: false
---

The process strikes me as interesting because of course sovereignty is an abstract concept, and what he gave away--access to Europe's finance markets, free movement of goods and personnel, the ability to sell fresh British goods on continental European markets--are all tangible benefits. It made me realize how much I expected the UK to act on tangible interests, not ideals--though it has to be noted that these were shitty ideals in the first place, sovereignty is still an ideal. Of course the trick to doing that is not to collect any data that would put the sanity of your plan into question. 

Two quotes stand out: "According to government officials, successive chancellors Sajid Javid and Rishi Sunak stopped officials carrying out a new analysis of the proposed deal, which would have come to the awkward conclusion that Britain would be left worse off." And: "Three people actively involved in lobbying government on behalf of industry told the Financial Times that chief executives who confronted ministers too overtly found that they were dropped off future conference calls."

And then of course there is the poison pill: the freedom clause that Boris Johnson had introduced last minute. [Which the EU promptly threatened to trigger this week with regard to Covid vaccine exports.](https://www.theguardian.com/uk-news/2021/jan/29/explainer-what-is-article-16-of-the-northern-ireland-protocol) Hilarious! [The EU has walked back on that threat yesterday](https://www.bbc.com/news/uk-55865539)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

